### ISSUE TITLE
Changing the speed of "Walk"

### ISSUE THREAD

**Issue by Jakob0330** [PetoiCamp/OpenCat#36]
I'm currently working on a project with Bittle. I want to change the speed of walking but haven't found parameters for speed of this action in the skillfile. Does anyone solve this problem before？

**Comment by borntoleave** [comment]
You can change the walking speed in many ways:
- Use faster gaits such as trot.
- Add delays between frames to slow the speed down. 
<img width="1027" alt="delayInSkills" src="https://user-images.githubusercontent.com/9747608/214587150-92b9384c-7089-4009-8fde-4d95a5d7f55c.png">

- Re-generate the walking gait with different numbers of frames. The fewer frames, the faster; the more frames, the slower and smoother. However, due to the limited memory size of NyBoard, the frames should be less than (450-4)/8 = 55, as the array to store the gait is defined by `int8_t *dataBuffer = new int8_t[450];` in src/OpenCat.h
- Buy the [ESP32-based BiBoard](https://www.petoi.com/products/petoi-biboard-esp32-development-board) with a faster CPU and a larger memory. The code can be found in [https://github.com/PetoiCamp/OpenCatEsp32](https://github.com/PetoiCamp/OpenCatEsp32)
